#!/bin/bash
set -e

NODEJS="node"
FILENAME="magic"
BUILD_DIR="./build"
DEFAULT_DIR="/usr/local/bin"
INSTALL_DIR=""

#
# Check if node is installed
#
command -v $NODEJS >/dev/null 2>&1 || {
	echo "Can't find '$NODEJS' (Node.js binary), is it installed? Is it in your PATH?" >&2
	exit 1
}

# Ensure a fresh build
if [[ -d "$BUILD_DIR" ]]; then
	rm -rf "$BUILD_DIR"
fi
echo "building magic..."
tsc
if [ -z "$1" ]; then
	INSTALL_DIR="$DEFAULT_DIR"
else
	INSTALL_DIR="$1"
fi
if [ ! -d "$INSTALL_DIR" ]; then
	mkdir "$INSTALL_DIR"
fi
echo "installing..."
echo "#!/usr/bin/env node" > "$BUILD_DIR/$FILENAME"
cat "$BUILD_DIR/magic.js" >> "$BUILD_DIR/$FILENAME"
chmod 755 "$BUILD_DIR/$FILENAME"
mv -f "$BUILD_DIR/$FILENAME" "$INSTALL_DIR"
echo "installed magic to '$INSTALL_DIR'"
